angular.module("AppAnime").controller("RenderingCtrl",['$scope',function($scope){
    $scope.imagePreview="default.jpg"
    $scope.videoPreview=null;
    $scope.thumbnailResult=null;
    $scope.animeResult=null;
    $scope.allAnimeResult=[];
    $scope.setAllAnimeResult=function(animes){
        $scope.allAnimeResult=animes;
    }
    $scope.setImagePreview=function(image){
        $scope.imagePreview=image;
    };
    $scope.setResumoResult=function(resume){
        $scope.animeResult=resume;
    }
    $scope.setThumbnailResult=function(thumbnail){
        $scope.thumbnailResult=thumbnail;
    };
    $scope.setVideoPreview=function(video){
        $scope.videoPreview=video;
    }
}]);